# 1. ndim
 1. ndim means number of dimensions.

 2. It tells us the dimensionality of an array.

  3. 1D array has ndim = 1.

  4. 2D array has ndim = 2.

  5. 3D array has ndim = 3.

In [17]:
import numpy as np
arr=np.array([111,222,333,444,555])
print(arr)
arr.ndim

arr2= np.array([[222,333,444,555],[666,777,888,999]])
print(arr2)
arr2.ndim

[111 222 333 444 555]
[[222 333 444 555]
 [666 777 888 999]]


2

In [12]:
arr.ndim

1

In [18]:
arr2.ndim

2

# 2. shape

 1. shape tells us the structure of an array.

 2. For a 2D array, shape is written as:    (rows, columns)

 3. shape returns a tuple.

 4. shape is very useful when working with datasets.

In [23]:
arr4=np.array([2222,3333,4444,5555])
print(arr4)
arr4.shape

[2222 3333 4444 5555]


(4,)

In [25]:
arr5=np.array([[2222,3333,44444,55555],[6666,7777,8888,9999],[1234,5678,1234,6253]])
print(arr5)
arr5.shape

[[ 2222  3333 44444 55555]
 [ 6666  7777  8888  9999]
 [ 1234  5678  1234  6253]]


(3, 4)

# 3. size
1. size gives the total number of elements.

 2. It counts all elements in the array.

 3. For a 2D array:    rows × columns = total elements.

In [28]:
arr=np.array([3333,4444,5555,66666,77777])
print(arr)
arr.size


[ 3333  4444  5555 66666 77777]


5

In [29]:
# 4. dtype
# 1. dtype tells us the data type of array elements.

# 2. Common NumPy data types include:
#    int
#    float
#    bool
#    str

# 3. NumPy arrays normally store elements of the same data type.

# 4. dtype is useful for understanding the type of data stored in an array.

In [32]:
arr=np.array([2212,12123,4434,4254,64256])
print(arr)
arr.dtype

[ 2212 12123  4434  4254 64256]


dtype('int32')

In [40]:
arr=np.array([12121,23232,343434,564545,6456435])
print(arr)
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

[  12121   23232  343434  564545 6456435]
(5,)
1
5
int32


In [47]:
arr2_2d=np.array([[12121212],[343434343],[532323],[23423423]])
print(arr2_2d)
print(arr2_2d.ndim)
print(arr2_2d.size)
print(arr2_2d.shape)
print(arr2_2d.dtype)

[[ 12121212]
 [343434343]
 [   532323]
 [ 23423423]]
2
4
(4, 1)
int32


In [54]:
arr3=np.array([[23,34,45,5656],[34,56,23,454],[2323,5454,2323,5454],[5656,4325,536,3432]])
print(arr3)
print(arr3.ndim)
print(arr3.size)
print(arr3.shape)
print(arr3.dtype)

[[  23   34   45 5656]
 [  34   56   23  454]
 [2323 5454 2323 5454]
 [5656 4325  536 3432]]
2
16
(4, 4)
int32


In [55]:
# ============================================================
# INTERVIEW POINTS
# ============================================================

# Q1. What does ndim do?
# ndim returns the number of dimensions of an array.

# Q2. What does shape do?
# shape returns the size of the array along each dimension.

# Q3. What does size do?
# size returns the total number of elements in an array.

# Q4. What does dtype do?
# dtype returns the data type of the elements in an array.

# Q5. What is the difference between shape and size?
# shape tells us the structure of an array,
# while size tells us the total number of elements.

# Q6. What is the difference between ndim and shape?
# ndim tells us the number of dimensions,
# while shape tells us the size along each dimension.