# The important array creation functions are:
 1. np.zeros()
 2. np.ones()
 3. np.arange()
 4. np.linspace()
 5. np.random.randint()
 6. np.random.rand()

# 1. np.zeros()
 1. np.zeros() creates an array filled with zeros.

 2. It can create both 1D and 2D arrays.

 3. np.zeros(5) creates 5 zeros.

 4. np.zeros((2, 3)) creates 2 rows and 3 columns.

 5. It is useful when we need an empty array initialized with zero values.


In [7]:
import numpy as np
arr=np.zeros(10)
print(arr)

arr=np.zeros((10,20))
print(arr)

arr=np.zeros((5,4))
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# 2. np.ones()
 1. np.ones() creates an array filled with ones.

 2. np.ones(5) creates 5 ones.

 3. np.ones((2, 3)) creates 2 rows and 3 columns.

 4. It is useful when we need an array initialized with one values.



In [11]:
arr=np.ones(10)
print(arr)

arr=np.ones((5,5))
print(arr)

arr=np.ones((10,10))
print(arr)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


# 3. np.arange()

 1. np.arange() creates a sequence of numbers.

 2. It can use start, stop and step values.

 3. The stop value is not included.

 4. Syntax:   np.arange(start, stop, step)

 5. It is useful for creating numerical sequences.


In [17]:
arr=np.arange(0,11,2)
print(arr)

arr=np.arange(5,51,5)
print(arr)

arr=np.arange(10,101,10)
print(arr)

arr=np.arange(8,81,8)
print(arr)

arr=np.arange(12,121,12)
print(arr)

[ 0  2  4  6  8 10]
[ 5 10 15 20 25 30 35 40 45 50]
[ 10  20  30  40  50  60  70  80  90 100]
[ 8 16 24 32 40 48 56 64 72 80]
[ 12  24  36  48  60  72  84  96 108 120]


# 4. np.linspace()
 1. np.linspace() creates evenly spaced values.

 2. It uses start, stop and number of values.

 3. The stop value is included by default.

 4. Syntax:   np.linspace(start, stop, num)

 5. It is useful when we need a fixed number of evenly spaced values.


In [21]:
arr= np.linspace(1,20,100)
print(arr)

arr=np.linspace(10,20,50)
print(arr)

[ 1.          1.19191919  1.38383838  1.57575758  1.76767677  1.95959596
  2.15151515  2.34343434  2.53535354  2.72727273  2.91919192  3.11111111
  3.3030303   3.49494949  3.68686869  3.87878788  4.07070707  4.26262626
  4.45454545  4.64646465  4.83838384  5.03030303  5.22222222  5.41414141
  5.60606061  5.7979798   5.98989899  6.18181818  6.37373737  6.56565657
  6.75757576  6.94949495  7.14141414  7.33333333  7.52525253  7.71717172
  7.90909091  8.1010101   8.29292929  8.48484848  8.67676768  8.86868687
  9.06060606  9.25252525  9.44444444  9.63636364  9.82828283 10.02020202
 10.21212121 10.4040404  10.5959596  10.78787879 10.97979798 11.17171717
 11.36363636 11.55555556 11.74747475 11.93939394 12.13131313 12.32323232
 12.51515152 12.70707071 12.8989899  13.09090909 13.28282828 13.47474747
 13.66666667 13.85858586 14.05050505 14.24242424 14.43434343 14.62626263
 14.81818182 15.01010101 15.2020202  15.39393939 15.58585859 15.77777778
 15.96969697 16.16161616 16.35353535 16.54545455 16

In [23]:
arr=np.linspace(100,10,5)
print(arr)

[100.   77.5  55.   32.5  10. ]


# 5. np.random.randint()
 1. It generates random integer values.

 2. The low value is included.

 3. The high value is not included.

 4. size tells us how many values or what shape of array we want.

5. The output can be different each time because the values are random.

6. Syntax: np.random.randint(low, high, size)



In [29]:
arr=np.random.randint(1,100,20)
print(arr)

arr= np.random.randint(1,50,10)
print(arr)

arr= np.random.randint(10,20,5)
print(arr)




[ 2 70 59 45 51 98 81  3  1 54 40 36 53 64  7 11 14 15  7 68]
[28 34  2  8 29 16 23 20 45  5]
[11 11 12 18 16]


In [31]:
arr=np.random.randint(1,10,(5,5))
print(arr)

[[8 3 9 1 8]
 [7 9 4 2 4]
 [2 2 3 6 9]
 [9 3 5 8 5]
 [3 1 6 6 7]]


# 6. np.random.rand()
 1. It generates random decimal values.

 2. Values are between 0 and 1.

 3. 0 can be included, but 1 is not included.

 4. We can create 1D or 2D arrays using this function.

 5. The output can be different each time because the values are random.


In [33]:
arr=np.random.rand(10)
print(arr)

[0.12486357 0.92193691 0.07067979 0.11757267 0.5522068  0.45484474
 0.20284385 0.07327493 0.98951555 0.04361592]


In [35]:
arr=np.random.rand(2,5)
print(arr)

[[0.47266516 0.20896886 0.77744168 0.75833695 0.87213732]
 [0.20143056 0.73114614 0.74379166 0.92102677 0.3149751 ]]


 np.zeros()        → Creates an array of zeros.

 np.ones()         → Creates an array of ones.

 np.arange()       → Creates a sequence with a step.

 np.linspace()     → Creates evenly spaced values.

 np.random.randint() → Creates random integers.

 np.random.rand()  → Creates random decimal values between 0 and 1.

In [55]:
arr=np.zeros(10)
print(arr)
arr=np.zeros((2,4))
print(arr)

arr=np.ones(10)
print(arr)
arr=np.ones((2,4))
print(arr)

arr=np.linspace(1,10,20)
print(arr)
arr=np.linspace(1,20,5)
print(arr)
arr=np.linspace(0,20,10)
print(arr)
arr=np.linspace(10,20,2)
print(arr)


arr=np.arange(3,31,3)
print(arr)
arr=np.arange(10,101,5)
print(arr)

arr=np.random.randint(1,20,10)
print(arr)
arr=np.random.randint(10,20,10)
print(arr)


arr=np.random.rand(10)
print(arr)
arr=np.random.rand(2,5)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]
[ 1.    5.75 10.5  15.25 20.  ]
[ 0.          2.22222222  4.44444444  6.66666667  8.88888889 11.11111111
 13.33333333 15.55555556 17.77777778 20.        ]
[10. 20.]
[ 3  6  9 12 15 18 21 24 27 30]
[ 10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90  95
 100]
[11 19  6 19 19  9  9 10 13  3]
[16 14 19 16 18 18 10 16 16 12]
[0.44504395 0.01859469 0.46315283 0.3358763  0.76707507 0.92736696
 0.30263994 0.9420637  0.62459497 0.04344919]
[[0.9489976  0.41899076 0.13530688 0.15784647 0.60410137]
 [0.61473536 0.47237279 0.25799791 0.73516591 0.46312836]]


np.zeros()          → 0 values

np.ones()           → 1 values

np.arange()         → Sequence + Step

np.linspace()       → Evenly spaced values

np.random.randint() → Random integers

np.random.rand()    → Random decimals (0 to 1)

In [65]:
# Q1. Create an array of 10 zeros.

arr=np.zeros(10)
print(arr)
# Q2. Create an array of 8 ones.

arr=np.ones(8)
print(arr)

# Q3. Create numbers from 1 to 20 using np.arange().

arr=np.arange(1,21,1)
print(arr)
# Q4. Create even numbers from 2 to 20 using np.arange().

arr=np.arange(2,21,2)
print(arr)
# Q5. Create 5 evenly spaced values between 0 and 100
#     using np.linspace().

arr=np.linspace(0,100,5)
print(arr)
# Q6. Generate 10 random integers between 1 and 50.

arr=np.random.randint(1,50,10)
print(arr)

# Q7. Generate a 2 × 3 array of random integers
#     between 10 and 100.

arr= np.random.randint(10,100,(2,3))
print(arr)
                       
# Q8. Generate 5 random decimal values between 0 and 1.

arr=np.random.rand(5)
print(arr)
# Q9. Create a 3 × 4 array filled with zeros.

arr=np.zeros((3,4))
print(arr)
# Q10. Create a 2 × 5 array filled with ones.
arr= np.ones((2,5))
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1.]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 2  4  6  8 10 12 14 16 18 20]
[  0.  25.  50.  75. 100.]
[ 7  5 36  6  9 10  4 10 29 15]
[[94 89 49]
 [51 41 27]]
[0.28563748 0.86771066 0.53326055 0.07406189 0.5920008 ]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
