What is NumPy?
- NumPy stands for Numerical Python.
- NumPy is a Python library used for working with numerical data.
- NumPy provides a powerful data structure called an array.
- NumPy is mainly used for mathematical and numerical operations.
- NumPy is one of the most important libraries for Data Analysis.


 NumPy can be used for:
 
 - Mathematical calculations
 - Statistical calculations
  - Array operations
  - Data filtering
  - Data transformation
  - Working with numerical datasets



In Jupyter Notebook, we can also use:
# !pip install numpy

In [4]:
import numpy as np

In [6]:
print(np)

<module 'numpy' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\numpy\\__init__.py'>


In [8]:
import numpy as np 
arr= np.array([1,2,3,4,5,6])
print(arr)

[1 2 3 4 5 6]


In [16]:
# 2. Create a NumPy array containing:
#    10, 20, 30, 40, 50

arr= np.array([10,20,30,40,50])
print(arr)

# 3. Print the array.

arr2 = np.array([222,333,444,555,666])
print(arr2)

# 4. Create another array containing:
#    5, 10, 15, 20, 25
arr3 = np.array([5,10,15,20,25])
print(arr3)

# 5. Print the second array.
arr4 = np.array([1100 , 110000, 110000 ,1100000])
print(arr4)



[10 20 30 40 50]
[222 333 444 555 666]
[ 5 10 15 20 25]
[   1100  110000  110000 1100000]


What is a NumPy Array?
- A NumPy array is a data structure used to store multiple values in a single object.
- NumPy arrays are mainly used to store and process numerical data.
- We create a NumPy array using the np.array() function.
- np.array() is used to create a NumPy array.
- It can convert a Python list into a NumPy array.
- Syntax: np.array(list)


In [22]:
arr=np.array([111,222,333,444,555,666])
print(arr)

list=[11,22,33,44,55,66]
arr2=np.array(list)
print(arr2)

[111 222 333 444 555 666]
[11 22 33 44 55 66]


In [24]:
# 1. np.array() creates a NumPy array.
arr=np.array([1111,2222,3333,4444])
print(arr)

# 2. It can convert a Python list into a NumPy array.
list=[100,200,300,400]
arr=np.array(list)
print(arr)



[1111 2222 3333 4444]
[100 200 300 400]


# 1D Array
 -A 1D array has only one dimension.
 
 -It looks similar to a single list of values.



In [26]:
arr_1d=np.array([2000,3000,4000,5000])
print(arr_1d)

[2000 3000 4000 5000]


# 2D Arra

 1. A 2D array has rows and columns.

 
 2. It looks like a table or matrix.
 
 3. It is commonly used to represent tabular numerical data.
 
 4. Each row can contain multiple values.

In [41]:
arr_2d = np.array([[1,2,3],[4,5,6]])
print(arr_2d)

arr2_2d= np.array([[11,22,33],[44,55,66],[77,88,99]])
print(arr2_2d)

arr2_2d.ndim
# ndim       → tells the number of dimensions

[[1 2 3]
 [4 5 6]]
[[11 22 33]
 [44 55 66]
 [77 88 99]]


2

In [46]:
# Q1. Create a 1D array containing:
# 10, 20, 30, 40, 50

arr=np.array([10,20,30,40,50])
print(arr)

# Q2. Create a 2D array with:
# [10, 20, 30]
# [40, 50, 60]

arr2= np.array([[10,20,30],[40,50,60]])
print(arr2)

# Q4. Print the dimension of the 1D array.
arr_1d=np.array([2200,3300,4400,5500,6600])
print(arr_1d)

# Q5. Print the dimension of the 2D array.
arr_2d=np.array([[2222,3333,4444,5555],[6666,7777,8888,9999]])
print(arr_2d)



[10 20 30 40 50]
[[10 20 30]
 [40 50 60]]
[2200 3300 4400 5500 6600]
[[2222 3333 4444 5555]
 [6666 7777 8888 9999]]


In [ ]:
# INTERVIEW POINTS

# Q1. What is a NumPy array?
# A NumPy array is a data structure used to store and process multiple values efficiently.

# Q2. What is np.array()?
# np.array() is a function used to create a NumPy array.

# Q3. What is ndarray?
# ndarray stands for N-dimensional array.
# It is the main array object in NumPy.

# Q4. What is a 1D array?
# A 1D array has one dimension and contains
# values in a single sequence.

# Q5. What is a 2D array?
# A 2D array has rows and columns.

# Q6. What is a 3D array?
# A 3D array is a collection of 2D arrays.

# Q7. How can you check the number of dimensions?
# We can use the ndim attribute.

# Example:
# arr.ndim